workspace:
  base: /node
  path: drone/node-example
  # path: /drone/src/github.com/go-training/..

clone:
  git:
    image: plugins/git
    depath: 50
    tags: true

pipeline:
  node:
    image: node:8.3.0
    group: testing
    commands:
      - yarn install
      - touch /node/drone/node-example/src/basicweb/Web.java

  ls:
    image: node:8.3.0
    group: testing
    commands:
      - ls -al /node/drone/node-example/src/basicweb/
  
  backend:
    image: node:8.3.0
    group: testing
    commands:
      - echo "backend testing123"

  node1:
    image: node:8.3.0
    group: build
    commands:
      - sleep 5
      - echo "sleep 5"

  node2:
    image: node:8.3.0
    group: build
    commands:
      - sleep 10
      - echo "sleep 10"

  node3:
    image: node:8.3.0
    group: build
    commands:
      - sleep 15
      - echo "sleep 15"
