workspace:
  base: /node
  path: drone/node-example

clone:
  git:
    image: plugins/git
    depath: 50
    tags: true

pipeline:
  node:
    image: node:8.3.0
    commands:
      - yarn install
      - touch /nosrcde/a.txt

  ls:
    image: node:8.3.0
    commands:
      - ls -al /src/basicweb