workspace:
  base: /node
  path: drone/node-example
  # path: /drone/src/github.com/go-training/..

clone:
  git:
    image: plugins/git
    depath: 50
    tags: true

pipeline:
  node:
    image: node:8.3.0
    commands:
      - yarn install
      - touch /drone/node-example/src/basicweb/Web.java

  ls:
    image: node:8.3.0
    commands:
      - ls -al /node/drone/node-example/src/basicweb/